# Generated by Django 5.0.3 on 2024-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('cognom', models.CharField(max_length=30)),
                ('edat', models.IntegerField()),
                ('rol', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=90)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
    ]
